// =============================================================================
// COMPANY PROFILE - Structured description that drives all data generation
// =============================================================================

/**
 * A CompanyProfile is the central config object for any B2B SaaS company.
 * It drives synthetic data generation, ontology derivation, and context building.
 * Can be generated by Claude from a natural language description, loaded from
 * a preset, or provided manually.
 */
export interface CompanyProfile {
  // Identity
  name: string;
  description: string;
  website?: string;
  country: string;
  currency: string; // ISO 4217: "EUR", "USD", "GBP", etc.
  currency_symbol: string; // "€", "$", "£", etc.

  // Business model
  business_model: "subscription" | "usage_based" | "hybrid" | "marketplace";
  primary_value_metric: string; // e.g. "shipping labels", "API calls", "seats"
  secondary_value_metrics: string[];

  // Scale (these define the synthetic dataset size)
  total_customers: number;
  total_arr: number;
  avg_deal_size: number;

  // Customer segments (3-5 segments, shares must sum to ~1.0)
  segments: CompanySegmentProfile[];

  // Products offered
  products: CompanyProductProfile[];

  // Pricing tiers (3-6 tiers, ordered low to high)
  pricing_tiers: CompanyTierProfile[];

  // Market & competitive context (populated by Claude web research)
  market_context?: MarketContext;
  competitors?: CompetitorProfile[];
  strategic_positioning?: StrategicPositioning;
}

export interface CompanySegmentProfile {
  name: string;
  description: string;
  customer_share: number; // 0-1, all segments must sum to ~1.0
  revenue_share: number; // 0-1, all segments must sum to ~1.0
  avg_mrr: number;
  churn_rate: number; // Monthly churn rate, e.g. 0.02 = 2%
  expansion_rate: number; // Monthly expansion rate, e.g. 0.15 = 15%
  value_drivers: string[];
  company_size: "startup" | "smb" | "mid_market" | "enterprise";
}

export interface CompanyProductProfile {
  name: string;
  type: "subscription" | "usage" | "one_time";
  base_price: number;
  unit_label?: string; // e.g. "label", "email", "API call", "seat"
}

export interface CompanyTierProfile {
  name: string;
  price_monthly: number;
  price_annual?: number;
  features: string[];
  value_metric_limits: Record<string, number | "unlimited">;
  customer_share: number; // 0-1
  revenue_share: number; // 0-1
  position: number; // 1 = lowest tier, ascending
}

export interface MarketContext {
  market_category: string; // e.g. "Shipping & Logistics SaaS"
  tam_estimate?: string; // e.g. "$4.2B"
  growth_rate?: string; // e.g. "12% CAGR"
  market_structure: string; // e.g. "Fragmented", "Oligopolistic", "Consolidated"
  key_trends: string[];
  buying_factors: string[]; // What matters to buyers in this market
}

export interface CompetitorProfile {
  name: string;
  website?: string;
  positioning: string; // One-line positioning statement
  pricing_model: string; // e.g. "Freemium + usage", "Enterprise-only", "Flat-rate SaaS"
  price_range?: string; // e.g. "$0-499/mo"
  key_differentiators: string[];
  estimated_market_share?: string;
}

export interface StrategicPositioning {
  value_proposition: string;
  target_segments: string[];
  key_advantages: string[];
  key_risks: string[];
  pricing_philosophy: string; // e.g. "Value-based", "Penetration", "Premium", "Competitive"
}

// =============================================================================
// PRESET TYPES
// =============================================================================

export type PresetId = "myparcel" | "devtools";

export interface PresetDefinition {
  id: PresetId;
  label: string;
  subtitle: string;
  description: string;
  profile: CompanyProfile;
}
